'use client'

import { CheckCircle2, ChevronDown } from 'lucide-react'
import { useState } from 'react'
import { completeProjectAction, createTaskAction } from '@/actions/work'
import { TaskCard } from '@/components/tasks/TaskCard'

export function ProjectCard({ project, workspaceId, tasks, initiallyOpen = false }: { project: { id: string; title: string; description: string | null; due_date: string | null }; workspaceId: string; tasks: { id: string; title: string; status: string; due_date: string | null; due_time: string | null }[]; initiallyOpen?: boolean }) {
  const [open, setOpen] = useState(initiallyOpen)
  return <article className="rounded-2xl bg-card p-5 shadow-sm"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><h2 className="font-bold">{project.title}</h2><p className="mt-1 text-sm text-muted-foreground">{project.description || 'No description'} {project.due_date && `- Due ${project.due_date}`}</p></div><form action={completeProjectAction}><input type="hidden" name="id" value={project.id}/><button title="Mark project completed" className="rounded-lg p-2 text-emerald-600 hover:bg-emerald-100"><CheckCircle2 className="size-5"/></button></form></div><button type="button" onClick={() => setOpen((value) => !value)} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-blue-600 hover:underline"><ChevronDown className={`size-4 transition-transform ${open ? 'rotate-180' : ''}`}/>{open ? 'Hide' : 'Show'} tasks ({tasks.length})</button>{open && <div className="mt-4 border-t pt-4"><form action={createTaskAction} className="grid gap-2 sm:grid-cols-[1fr_auto_auto_auto]"><input type="hidden" name="workspaceId" value={workspaceId}/><input type="hidden" name="projectId" value={project.id}/><input required name="title" placeholder="Add a task" className="h-10 rounded-xl border bg-transparent px-3"/><input name="dueDate" type="date" max={project.due_date ?? undefined} className="h-10 rounded-xl border bg-transparent px-2 text-sm"/><input name="dueTime" type="time" className="h-10 rounded-xl border bg-transparent px-2 text-sm"/><button className="rounded-xl bg-purple-600 px-3 text-sm font-semibold text-white">Add</button></form><ul className="mt-4 space-y-3">{tasks.map((task) => <TaskCard key={task.id} task={task} projectDueDate={project.due_date}/>)}{!tasks.length && <li className="text-sm text-muted-foreground">No open tasks.</li>}</ul></div>}</article>
}