'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

async function context() { const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect('/login'); return {supabase,user} }
function text(form:FormData,key:string){return String(form.get(key)??'').trim()}
function refresh(){ for (const path of ['/','/tasks/projects','/tasks/goals','/tasks/notes','/calendar','/completed']) revalidatePath(path) }
export async function createProjectAction(form:FormData){const {supabase,user}=await context();const workspaceId=text(form,'workspaceId'),title=text(form,'title');if(!workspaceId||!title)return;const {error}=await supabase.from('projects').insert({workspace_id:workspaceId,created_by:user.id,title,description:text(form,'description')||null,due_date:text(form,'dueDate')||null,due_time:text(form,'dueTime')||null});if(error)throw new Error(error.message);refresh()}
export async function createTaskAction(form:FormData){const {supabase,user}=await context();const workspaceId=text(form,'workspaceId'),title=text(form,'title'),projectId=text(form,'projectId'),goalId=text(form,'goalId');if(!workspaceId||!title)return;const {error}=await supabase.from('tasks').insert({workspace_id:workspaceId,created_by:user.id,title,project_id:projectId||null,goal_id:goalId||null,due_date:text(form,'dueDate')||null,due_time:text(form,'dueTime')||null});if(error)throw new Error(error.message);refresh()}
export async function updateTaskStatusAction(form:FormData){const {supabase}=await context();const id=text(form,'id'),status=text(form,'status');if(!['pending','in_progress','completed','cancelled','postponed'].includes(status))return;const {error}=await supabase.from('tasks').update({status}).eq('id',id);if(error)throw new Error(error.message);refresh()}
export async function completeTaskAction(form:FormData){const {supabase}=await context();const id=text(form,'id');if(!id)return;const {error}=await supabase.from('tasks').update({status:'completed'}).eq('id',id);if(error)throw new Error(error.message);refresh()}
export async function completeProjectAction(form:FormData){const {supabase}=await context();const id=text(form,'id');if(!id)return;const {error}=await supabase.from('projects').update({status:'completed'}).eq('id',id);if(error)throw new Error(error.message);refresh()}
export async function createGoalAction(form:FormData){const {supabase,user}=await context();const workspaceId=text(form,'workspaceId'),title=text(form,'title'),targetDate=text(form,'targetDate');if(!workspaceId||!title||!targetDate)return;const {error}=await supabase.from('goals').insert({workspace_id:workspaceId,user_id:user.id,created_by:user.id,title,target_date:targetDate,term:text(form,'term')||'short_term'});if(error)throw new Error(error.message);refresh()}
export async function createNoteAction(form:FormData){const {supabase,user}=await context();const workspaceId=text(form,'workspaceId'),title=text(form,'title'),taskId=text(form,'taskId'),projectId=text(form,'projectId');if(!workspaceId||!title)return;const {error}=await supabase.from('notes').insert({workspace_id:workspaceId,created_by:user.id,title,body:text(form,'body'),task_id:taskId||null,project_id:taskId?null:projectId||null});if(error)throw new Error(error.message);refresh()}
export async function updateNoteAction(form:FormData){const {supabase}=await context();const id=text(form,'id'),title=text(form,'title'),taskId=text(form,'taskId'),projectId=text(form,'projectId');if(!id||!title)return;const {error}=await supabase.from('notes').update({title,body:text(form,'body'),task_id:taskId||null,project_id:taskId?null:projectId||null}).eq('id',id);if(error)throw new Error(error.message);refresh()}
export async function addFeedbackAction(form:FormData){const {supabase,user}=await context();const workspaceId=text(form,'workspaceId'),message=text(form,'message'),taskId=text(form,'taskId'),projectId=text(form,'projectId');if(!workspaceId||!message||(!taskId&&!projectId))return;const {error}=await supabase.from('accountability_feedback').insert({workspace_id:workspaceId,author_id:user.id,message,kind:text(form,'kind')||'question',task_id:taskId||null,project_id:projectId||null});if(error)throw new Error(error.message);refresh()}
export async function updateTaskScheduleAction(form:FormData){const {supabase}=await context();const id=text(form,'id');const dueDate=text(form,'dueDate')||null;const dueTime=text(form,'dueTime')||null;const {error}=await supabase.from('tasks').update({due_date:dueDate,due_time:dueTime}).eq('id',id);if(error)throw new Error(error.message);refresh()}

export async function updateGoalAction(form:FormData){const {supabase}=await context();const id=text(form,'id'),status=text(form,'status'),targetDate=text(form,'targetDate');if(!id||!['not_started','in_progress','achieved','postponed','cancelled'].includes(status))return;const {data:goal,error:readError}=await supabase.from('goals').select('target_date').eq('id',id).single();if(readError)return;const effectiveDate=targetDate||goal.target_date;if(!effectiveDate)return;const {error}=await supabase.from('goals').update({status,target_date:effectiveDate}).eq('id',id);if(error)return;refresh()}
export async function completeGoalAction(form:FormData){const {supabase}=await context();const id=text(form,'id');if(!id)return;const {error}=await supabase.from('goals').update({status:'achieved'}).eq('id',id);if(error)throw new Error(error.message);refresh()}
