'use client'

import { Plus, X } from 'lucide-react'
import { useState } from 'react'
import { createCalendarEventAction, createGoalAction, createProjectAction } from '@/actions/work'

function Toggle({ label, open, setOpen }: { label: string; open: boolean; setOpen: (open: boolean) => void }) { return <button type="button" onClick={() => setOpen(!open)} className="inline-flex h-11 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-semibold text-white hover:bg-blue-500">{open ? <X className="size-4"/> : <Plus className="size-4"/>}{open ? 'Close form' : label}</button> }
export function NewProjectForm({ workspaceId }: { workspaceId: string }) { const [open, setOpen] = useState(false); return <div><Toggle label="Add new project" open={open} setOpen={setOpen}/>{open && <form action={createProjectAction} className="mt-4 rounded-2xl bg-card p-5 shadow-sm"><input type="hidden" name="workspaceId" value={workspaceId}/><h2 className="font-bold">New project</h2><input required name="title" placeholder="Project name" className="mt-4 h-11 w-full rounded-xl border bg-transparent px-3"/><textarea name="description" placeholder="Description" className="mt-3 min-h-24 w-full rounded-xl border bg-transparent p-3"/><input name="dueDate" type="date" className="mt-3 h-11 w-full rounded-xl border bg-transparent px-3"/><button className="mt-3 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Create project</button></form>}</div> }
export function NewGoalForm({ workspaceId }: { workspaceId: string }) { const [open, setOpen] = useState(false); return <div><Toggle label="Add new goal" open={open} setOpen={setOpen}/>{open && <form action={createGoalAction} className="mt-4 rounded-2xl bg-card p-5 shadow-sm"><h2 className="font-bold">New goal</h2><input type="hidden" name="workspaceId" value={workspaceId}/><input required name="title" placeholder="Goal title" className="mt-4 h-11 w-full rounded-xl border bg-transparent px-3"/><textarea name="description" placeholder="Description" className="mt-3 min-h-24 w-full rounded-xl border bg-transparent p-3"/><input required name="targetDate" type="date" className="mt-3 h-11 w-full rounded-xl border bg-transparent px-3"/><select name="term" className="mt-3 h-11 w-full rounded-xl border bg-transparent px-3"><option value="short_term">Short term</option><option value="long_term">Long term</option></select><button className="mt-4 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Create goal</button></form>}</div> }
export function NewReminderForm({ workspaceId }: { workspaceId: string }) { const [open, setOpen] = useState(false); return <div><Toggle label="Add new reminder" open={open} setOpen={setOpen}/>{open && <form action={createCalendarEventAction} className="mt-4 rounded-2xl bg-card p-5 shadow-sm"><input type="hidden" name="workspaceId" value={workspaceId}/><input type="hidden" name="eventKind" value="reminder"/><h2 className="font-bold">New reminder</h2><input required name="title" placeholder="Reminder title" className="mt-4 h-11 w-full rounded-xl border bg-transparent px-3"/><input required name="date" type="date" className="mt-3 h-11 w-full rounded-xl border bg-transparent px-3"/><input name="time" type="time" className="mt-3 h-11 w-full rounded-xl border bg-transparent px-3"/><button className="mt-4 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Create reminder</button></form>}</div> }